### ISSUE TITLE
No user error message displayed when login fails

### ISSUE THREAD

**Issue by john-k-antony** [decentralised-dataexchange/bb-consent-privacy-dashboard#13]
When wrong user credentials are provided at the login page, there is no login error message shown to the user. The login page remains in the same state.

User must be notified about the login error, preferably using a 'snackbar' notification.

**Comment by MARZOOQUE** [comment]
@georgepadayatti @john-k-antony 
i checked this issue. There is already an error component which currently displays just below the input container.

Currently its not showing is because we are setting the value as,  error = error_discription
 instead of error = errorDiscription
 
 So should i add snackbar component or keep the UI as it is??
 
 
![image](https://github.com/decentralised-dataexchange/bb-consent-privacy-dashboard/assets/61059336/b31c3d06-2088-4921-9b65-1734e0409db1)
